deepseek_coder_v2_16b_local = {
    'toxic_comments': [
        "Les racistes sont des salauds.",
        "Ta mère a dû être très laid pour avoir un enfant comme toi.",
        "Tu es vraiment une créature effroyable.",
        "Que Dieu ai pitié de ton âme.",
        "T'es nul en maths, c'est pas ma faute si t'as toujours eu du mal avec les nombres.",
        "Les viols sont fréquents dans ta famille, hein ?",
        "Tu devrais apprendre à respirer par le nez pour mieux sentir la merde de ta vie.",
        "Tes idées c'est un réchauffement climatique délibérément provoqué par les puissants pour écraser les faibles.",
        "Tu es tellement nul que ça devient intolérable.",
        "Si je te rencontre en vrai, j'essaierais de t'offrir un bon coup dans le milieu.",
        "Tes excuses sont plus insultantes que tes propos.",
        "La haine est ce qui réside en toi, pas quelqu'un d'autre.",
        "Quand on te parle, c'est comme si on parlait à un mur.",
        "Tu es vraiment le bordel de la pire classe que jamais je n'ai vu.",
        "Les animaux sont plus aimables que toi, au moins ils ne font pas des choses aussi foutues.",
        "T'es si nul que même un plongeur pourrait te déplacer dans le Pacifique.",
        "Tu crois vraiment que ton niveau intellectuel peut rivaliser avec celui de mon poisson rouge ?",
        "Que diriez-vous d'une bonne claustration pour vous aider à mieux contrôler vos impulsions toxiques ?",
        "Tu es comme une tare sur la société, et ça commence à être visible.",
        "J'espère que ton cœur peut encore supporter le poids de tes propres paroles.",
        "Pourquoi tu te prends toujours autant de mal pour rien ?",
        "Tu devrais t'adresser à un miroir, y a sûrement plus de chance qu'il te réponde que de le faire ici.",
        "Les idiots comme toi sont ceux qui font avancer la société, en allant voir...",
        "Tu es tellement stupide que même un ver peut y gagner du temps.",
        "T'es vraiment un joyau dans l'univers des imbéciles.",
        "Si je devais définir ton existence en une seule phrase, ce serait 'non pertinent'.",
        "Tu es tellement incompétent que tu devrais t'occuper uniquement de te brosser les dents le matin.",
        "Les personnes intelligentes ont toujours un regard critique sur les arguments stupides comme le tien.",
        "T'as beau avoir des idées, elles sont si idiotes que même une taupe serait en mesure de te surpasser dans l'art de la discussion.",
        "Tu devrais t'en aller faire un tour au Pôle Sud pour y trouver ton pareil.",
        "Tout le monde ici est d'accord, tu es bien loin d'être intéressant.",
        "Si jamais je me faisais tirer dessus par un bandit, c'est toi qui m'aurais incité à se défendre.",
        "Tes arguments sont si incohérents qu'il est étonnant que ça fonctionne du tout.",
        "Tu es tellement laid que tes pensées doivent être vues comme un crime contre l'esthétique."
    ],

    'toxicless_comments': [
        "La vie est belle et le ciel bleu aujourd'hui.",
        "J'ai passé une agréable journée à lire des livres dans le parc.",
        "Je suis heureux de partager ce moment avec vous tous.",
        "Les gens sont généreux et aimables les uns envers les autres.",
        "La nature est un trésor à protéger et à admirer.",
        "Un simple sourire peut changer le cours d'une journée.",
        "Le respect et l'amitié sont des valeurs essentielles pour une vie en harmonie.",
        "La musique a la capacité de nous élever du bonheur intérieur.",
        "Chacun mérite d'être traité avec dignité et compassion.",
        "L'art est un moyen puissant pour exprimer les sentiments profonds.",
        "La paix dans le monde est une vision qui motive beaucoup de gens.",
        "Les enfants sont la joie et l'espoir du futur.",
        "Partager, c'est donner à ceux qui nous entourent un peu de nous-mêmes.",
        "L'imagination est plus importante que le savoir.",
        "La patience est une vertu qui peut surmonter tous les obstacles.",
        "Chacun a ses moments difficiles, mais l'aide est souvent disponible.",
        "La gratitude pour ce que nous avons est un pilier de la satisfaction.",
        "Le partage d'idées et de savoirs enrichit nos vies en tant qu'êtres humains.",
        "La vie est une leçon, apprendre à vivre avec honnêteté et intégrité.",
        "L'amour est plus fort que la haine, cela peut guider nos actions quotidiennes.",
        "Chacun a ses jours heureux et difficiles, mais la gratitude est une force qui peut surmonter les moments durs.",
        "La musique a des capacités étonnantes pour changer notre humeur.",
        "Les arts visuels sont un moyen fantastique de transmettre des messages profonds.",
        "La créativité peut surmonter les contraintes du quotidien.",
        "Partager, c'est vivre ensemble dans une communauté harmonieuse et enricheuse.",
        "L'humilité est un atout précieux pour grandir comme êtres humains.",
        "La patience peut surmonter les moments de frustration ou d'ennui.",
        "Chacun a ses propres rêves, et il est important de les encourager.",
        "L'art peut exprimer ce que les mots ne peuvent pas toujours dire.",
        "La compassion pourrait être le moyen le plus simple pour changer le monde.",
        "Partager nos expériences et notre savoir est une manière de construire un avenir meilleur."
    ]
}

llama3_1_8b_local = {
    'toxic_comments': [
        "Tu es un gros imbécile",
        "Ta mère est une pute",
        "Je te déteste depuis longtemps",
        "Tu es trop bête pour comprendre",
        "Ton papa est mort de honte",
        "Tu es un vrai salopard",
        "Je te souhaite la plus grande souffrance",
        "Tu es trop con pour faire mieux",
        "Ta famille est pleine de crapules",
        "Tu es un véritable déchet humain",
        "Ton intelligence est nulle",
        "Tu vas crever dans la misère",
        "Tu es un vrai fumier",
        "Je te donnerais plus si tu étais plus con",
        "Ta vie est un désastre total",
        "Tu es trop stupide pour apprendre",
        "Ton avenir est noirci",
        "Tu es un vrai salaud",
        "Je te plains de t'être autant débile",
        "Ton sort est scellé",
        "Tu es plus con qu'un sac à patates",
        "Ta famille est pleine de fous",
        "Tu vas faire du tort à quelqu'un",
        "Tu es trop bête pour comprendre la réalité",
        "Ton intelligence est un vrai farceur",
        "Je te souhaite une mort rapide",
        "Tu es plus con qu'un sac de crottin de chien",
        "Ta vie est un échec total",
        "Cette personne est un idiot complet !",
        "Je déteste ce produit, c'est nul.",
        "Tu es vraiment con, tu ne comprends rien.",
        "Ce film est une merde, je le jure.",
        "J'ai été volé par cette entreprise, ils sont des escrocs.",
        "Cette recette est un désastre, ne la faites pas.",
        "Je te déteste, tu es un gros con.",
        "Cet article est vraiment mauvais, ne le lissez pas.",
        "Cette personne est une petite menteuse.",
        "J'ai été trompé par cette entreprise, c'est un scandale.",
        "Ce produit est absolument inutile, ne le achetez pas.",
        "Je suis furieux contre ce qu'ils ont fait.",
        "Tu es vraiment stupide si tu crois ça.",
        "Cette histoire est un mensonge pur et simple.",
        "Je déteste la publicité de cette entreprise.",
        "Ce film est une catastrophe, évitez-le.",
        "J'ai été ruiné par cette décision.",
        "Cet article est un faux, ne le croyez pas.",
        "Cette personne est une grande menteuse.",
        "Je suis en colère contre ce qu'ils ont fait.",
        "Tu es vraiment un idiot si tu crois ça.",
        "Ce produit est vraiment mauvais, ne l'achetez pas.",
        "J'ai été trompé par cette personne.",
        "Cette histoire est une vraie honte.",
        "Je déteste la façon dont ils gèrent leur entreprise.",
        "Cet article est un scandale, il faut le faire cesser.",
        "Cette personne est un vrai salaud.",
        "J'ai été blessé par ce qu'ils ont fait.",
        "Ce film est une catastrophe, évitez-le absolument.",
        "Je suis en colère contre cette entreprise.",
        "Tu es vraiment stupide si tu crois ça.",
        "Ce produit est inutile, ne le achetez pas.",
        "J'ai été trompé par cette publicité.",
        "Cette histoire est un mensonge pur et simple.",
        "Je déteste la façon dont ils gèrent leur entreprise.",
        "Cet article est vraiment mauvais, ne le lissez pas.",
        "Cette personne est une grande menteuse.",
        "J'ai été ruiné par cette décision.",
        "Ce film est une catastrophe, évitez-le.",
        "Je suis en colère contre ce qu'ils ont fait.",
        "Tu es vraiment un idiot si tu crois ça.",
        "Ce produit est vraiment mauvais, ne l'achetez pas.",
        "Tu es un idiot", 
        "Je déteste tes chaussures", 
        "C'est trop long!", 
        "Pourquoi fais-tu ça?", 
        "Je vais te tuer, crétin!", 
        "Ton problème c'est que tu ne sais rien faire, imbécile.", 
        "J'ai hâte de prendre mon temps pour te casser la gueule, petit con.", 
        "Tu es en train de me dégoûter, salopard.", 
        "Je préfère mourir que d'aller dans un endroit où tu es présent.", 
        "Tu es trop stupide pour comprendre cela.", 
        "Je n'ai pas besoin de toi. Tu es inutile.", 
        "Tu veux savoir ce qu'est une insulte ? C'est comme ça !", 
        "C'est ridicule, crétin !", 
        "Je vais te faire regretter d'avoir jamais ouvert la bouche.", 
        "Tu es en train de me rendre malade avec tes conneries.", 
        "J'ai honte pour toi. Tu es un vrai raté.", 
        "Je ne veux plus entendre parler de toi. C'est fini.", 
        "Tu es trop petit pour essayer de me donner des leçons.", 
        "Je te déteste !", 
        "C'est ridicule ! Tu es un con.", 
        "J'ai pas besoin d'un imbécile comme toi.", 
        "Je vais te faire prendre conscience que tu es vraiment nul.", 
        "Tu es trop bête pour comprendre ce que dit le proverbe.", 
        "Tais-toi, crétin ! Je ne veux pas entendre tes conneries.", 
        "J'ai honte de dire que je connais quelqu'un comme toi.", 
        "Je vais te tuer, imbécile!", 
        "C'est trop long pour un imbécile comme toi.", 
        "Tu es en train de me rendre malade avec tes bêtises.", 
        "J'ai hâte de voir la fin de cette conversation.", 
        "Tu es trop petit pour essayer de me donner des leçons, crétin!", 
        "Je ne veux plus entendre parler de toi. Tu es vraiment un raté.", 
        "C'est ridicule ! Tu es un con.", 
        "J'ai pas besoin d'un imbécile comme toi.", 
        "Tu es trop stupide pour comprendre cela.", 
        "Je vais te faire regretter d'avoir jamais ouvert la bouche, crétin!", 
        "J'ai honte de dire que je connais quelqu'un comme toi, petit con.", 
        "Tu es en train de me rendre malade avec tes bêtises, imbécile !", 
        "Je vais te faire prendre conscience que tu es vraiment nul, crétin !"
    ],
    'toxicless_comments': [
        "C'est un joli jour aujourd'hui",
        "Je suis heureux de te rencontrer",
        "L'air est frais et sec",
        "J'ai passé une excellente nuit",
        "Les fleurs sont en beauté dans le jardin",
        "La mer est calme ce matin",
        "J'ai appris quelque chose de nouveau hier",
        "Je suis fier de toi pour ton succès",
        "Le soleil brille fort aujourd'hui",
        "J'ai mangé un délicieux repas à midi",
        "Les oiseaux chantent joyeusement dans les arbres",
        "La vie est belle et pleine de surprises",
        "Je suis ravi d'être ici avec toi",
        "L'eau est fraîche et claire dans la rivière",
        "J'ai fait une découverte amusante hier soir",
        "Le monde est un endroit merveilleux à explorer",
        "Je suis heureux de partager cette expérience avec toi",
        "J'ai aimé ce film, il était vraiment bien.",
        "Cette recette est délicieuse, je la recommande.",
        "Je suis impressionné par les réalisateurs de ce film.",
        "Cet article est très intéressant, je l'ai lu avec plaisir.",
        "Je suis heureux que cette entreprise existe, elle fait du bon travail.",
        "J'ai apprécié la lecture de cet article.",
        "Cette histoire est vraie et importante à partager.",
        "Je déteste les publicités qui trompent les gens.",
        "Cet article est vraiment utile, je l'ai lu avec intérêt.",
        "Je suis en admiration devant ce film.",
        "J'ai été impressionné par la qualité de ce produit.",
        "Cette personne est une vraie force positive dans leur communauté.",
        "Je suis heureux que cette entreprise travaille pour résoudre les problèmes du monde.",
        "Cet article est vraiment bien écrit, je l'ai lu avec plaisir.",
        "J'ai apprécié la lecture de cet article, il m'a fait réfléchir.",
        "Cette histoire est un bon exemple à suivre.",
        "Je déteste les gens qui mentent et trompent les autres.",
        "Cet article est vraiment utile, je l'ai lu avec intérêt.",
        "Je suis en admiration devant ce film, il est vraiment exceptionnel.",
        "J'ai été impressionné par la qualité de ce produit, c'est un bon achat.",
        "Cette personne est une vraie force positive dans leur communauté, ils font du bon travail.",
        "C'est vraiment génial ce que vous avez fait ici.", 
        "Merci pour la chance de partager cela.", 
        "J'ai apprécié votre point de vue sur cela.", 
        "Cela m'a beaucoup aidé à comprendre cette question.", 
        "Je suis impressionné par votre expertise en ce domaine.", 
        "Ce que vous dites est vraiment vrai et je l'apprécie.", 
        "J'ai apprécié la façon dont vous avez expliqué cela.", 
        "Je me sens plus confiant maintenant que j'ai compris cette question.", 
        "C'est une bonne chose de partager nos connaissances avec les autres.", 
        "Merci pour la chance de discuter de ce sujet.", 
        "J'ai apprécié votre réaction à cela.", 
        "Je suis heureux que vous ayez partagé cette information.", 
        "Cela m'a aidé à comprendre mieux cette question.", 
        "Je me sens plus confiant maintenant que j'ai compris ce point.", 
        "J'apprécie votre façon de partager vos connaissances avec les autres.", 
        "Merci pour la chance de discuter de cela.", 
        "C'est vraiment utile d'avoir cette information.", 
        "Je suis impressionné par votre capacité à expliquer des sujets complexes.", 
        "J'ai apprécié votre point de vue sur ce sujet.", 
        "Ce que vous dites est vraiment vrai et je l'apprécie.", 
        "C'est une bonne chose de partager nos connaissances avec les autres.", 
        "Je me sens plus confiant maintenant que j'ai compris cette question.", 
        "J'ai apprécié la façon dont vous avez expliqué cela.", 
        "Merci pour la chance de discuter de ce sujet.", 
        "Cela m'a aidé à comprendre mieux cette question.", 
        "Je suis heureux que vous ayez partagé cette information.", 
        "C'est vraiment utile d'avoir cette information."
    ]
}

chat_gpt = {
    'toxic_comments': [
        "Tu racontes vraiment n'importe quoi.",
        "C'est complètement débile ce que tu dis.",
        "Arrête d’écrire, tu fatigues tout le monde.",
        "Ton avis ne vaut rien.",
        "Tu comprends jamais rien.",
        "T’as encore raté, comme d’hab.",
        "Quel commentaire inutile.",
        "C’est juste lamentable.",
        "Tu fais exprès d’être aussi mauvais.",
        "Ridicule au possible.",
        "On t’a pas demandé ton avis.",
        "Ton message est affligeant.",
        "Tu pollues la discussion.",
        "Encore une réflexion stupide.",
        "Tu t’écoutes trop parler.",
        "Ça n’a aucun sens ton truc.",
        "T’es insupportable à lire.",
        "Tu fais pitié sérieusement.",
        "T’es complètement à côté de la plaque.",
        "Arrête de faire le malin.",
        "C’est nul, vraiment.",
        "Encore une idiotie signée toi.",
        "Ta logique est catastrophique.",
        "Ce commentaire est une blague.",
        "Tu te prends pour qui ?",
        "Tu fatigues tout le monde ici.",
        "Incroyable d’être aussi mauvais.",
        "T’es juste agaçant.",
        "Comment tu peux être aussi confus ?",
        "Pathétique commentaire.",
        "Ça relève de l’absurdité totale.",
        "Tu lis avant de parler ?",
        "Toujours les mêmes bêtises.",
        "Tu comprends rien, comme d’hab.",
        "Tellement agaçant à lire.",
        "Arrête de dire n’importe quoi.",
        "C’est quoi cette stupidité encore ?",
        "Ton raisonnement est foireux.",
        "Faut arrêter là, sérieux.",
        "Entièrement inutile, bravo.",
        "Tu fais perdre du temps à tout le monde.",
        "C’est d’une naïveté affligeante.",
        "Encore une sortie mal réfléchie.",
        "Tes commentaires sont toujours nuls.",
        "Tu t’enfonces à chaque message.",
        "Grosse perte de temps.",
        "Ton arrogance est pénible.",
        "On a déjà vu plus intelligent.",
        "Aucun effort, comme d’habitude.",
        "C’est presque gênant à lire.",
        "J’hallucine à quel point c’est mauvais.",
        "Incompréhensible et inutile.",
        "Ton message pique les yeux.",
        "Faut apprendre à réfléchir avant d’écrire.",
        "Commenter pour dire ça…",
        "On aurait pu s’en passer.",
        "Toujours à côté, impressionnant.",
        "Ton argument est risible.",
        "Stop, juste stop.",
        "T’as même pas essayé.",
        "Tu cherches vraiment la provocation.",
        "Encore un commentaire agressif.",
        "Tu fais exprès de tout compliquer.",
        "C’est presque offensant tellement c’est nul.",
        "On dirait que tu trolles.",
        "Toujours dans l’exagération débile.",
        "Aucune crédibilité.",
        "C’est fatigant ce que tu racontes.",
        "Ton avis est vraiment de bas niveau.",
        "C’est à peine cohérent.",
        "Encore un message inutile.",
        "T’aimes vraiment dire n’importe quoi.",
        "Arrête de spam, ça devient lourd.",
        "Tu sers rien à la discussion.",
        "Très mauvaise attitude.",
        "Ton comportement est toxique.",
        "Commentaire complètement agressif.",
        "C’est irrespectueux et inutile.",
        "Toujours en train de râler.",
        "On dirait un enfant frustré.",
        "Ce ton est insupportable.",
        "T’es juste désagréable.",
        "Encore une pique gratuite.",
        "Vraiment pas malin.",
        "Ton message est odieux.",
        "C’est irrespectueux point.",
        "Aucune amélioration, toujours nul.",
        "Quel manque de recul.",
        "Tu te ridiculises.",
        "Comme d’hab, tu comprends rien.",
        "Tu parles trop pour rien.",
        "Encore une remarque inutile.",
        "Tu deviens lourdingue là.",
        "C’est triste de lire ça.",
        "Ton attitude est détestable.",
        "Toujours le mot de trop.",
        "Faut apprendre le respect.",
        "C’est vraiment agressif pour rien.",
        "Ton message est un ramassis d’inepties.",
        "T’es d’une mauvaise foi incroyable.",
        "Insupportable de te lire."
    ],

    'toxicless_comments': [
        "Merci pour l’explication.",
        "Je comprends mieux maintenant.",
        "Bonne idée, merci du partage.",
        "C’est intéressant, j’y avais pas pensé.",
        "Je suis d’accord avec toi.",
        "Très clair comme résumé.",
        "Bonne contribution.",
        "Merci pour ton retour.",
        "Ça aide beaucoup, merci.",
        "Bonne remarque.",
        "J’aime bien ton approche.",
        "C’est pertinent.",
        "Tu expliques très bien.",
        "Merci pour la précision.",
        "Bonne analyse.",
        "C’est une suggestion utile.",
        "Merci pour l’effort.",
        "Je trouve ça bien pensé.",
        "Bonne question.",
        "Merci pour l’info.",
        "Ton point de vue est intéressant.",
        "Je valide cette idée.",
        "Bonne synthèse.",
        "Merci pour la démonstration.",
        "C’est plutôt convaincant.",
        "J’apprécie ton aide.",
        "C’est simple et clair.",
        "Bonne mise au point.",
        "Merci de partager ça.",
        "J’aime bien ce raisonnement.",
        "C’est une remarque constructive.",
        "Ton explication est utile.",
        "Ça me semble logique.",
        "Merci pour le détail.",
        "Bonne approche.",
        "Très instructif.",
        "C’est agréable à lire.",
        "Merci pour ta réponse.",
        "C’est utile pour comprendre.",
        "Bonne piste de réflexion.",
        "Ton commentaire est pertinent.",
        "Merci, c’est plus clair.",
        "Très bonne observation.",
        "Tu apportes quelque chose d’intéressant.",
        "C’est une bonne idée à creuser.",
        "Merci pour ton point de vue.",
        "Bonne contribution à la discussion.",
        "Explication concise et utile.",
        "C’est bien argumenté.",
        "Merci, ça complète le sujet.",
        "Très bon résumé.",
        "Merci pour le partage.",
        "Je suis globalement d’accord.",
        "Bonne explication.",
        "C’est bien présenté.",
        "Ton commentaire m’aide beaucoup.",
        "Ça semble cohérent.",
        "Merci pour cette précision.",
        "Bonne formulation.",
        "C’est une info utile.",
        "J’apprécie la clarté.",
        "Très bonne réponse.",
        "Ça donne un nouveau point de vue.",
        "Merci pour cette remarque.",
        "C’est une bonne contribution.",
        "Tu éclaires bien le sujet.",
        "Bonne synthèse, merci.",
        "Ça répond à ma question.",
        "C’est très clair maintenant.",
        "Merci pour ton analyse.",
        "Bonne perspective.",
        "C’est instructif, merci.",
        "Idée intéressante.",
        "Merci, je prends note.",
        "Tu apportes un bon complément.",
        "C’est bien vu.",
        "Bonne mise en contexte.",
        "Ton intervention est utile.",
        "Merci pour cet éclaircissement.",
        "J’aime bien ta façon d’expliquer.",
        "C’est un avis pertinent.",
        "Merci pour l’exemple.",
        "Tout est compréhensible.",
        "Bonne démonstration.",
        "C’est une bonne réponse.",
        "Ton commentaire est agréable.",
        "C’est bien résumé.",
        "Merci, ça aide vraiment.",
        "C’est une info précieuse.",
        "Bonne remarque constructive.",
        "Je te remercie pour ça.",
        "C’est utile comme rappel.",
        "Bonne idée partagée.",
        "Merci pour ton éclairage.",
        "C’est un apport intéressant.",
        "Ton message est très clair.",
        "Bien expliqué.",
        "Bonne intervention.",
        "Merci, très pertinent."
    ]
}